### ISSUE TITLE
Clean up expired items.

### ISSUE THREAD

**Issue by vwochnik** [DavidGoodwin/RateLimit#5]
How to clean up expired items?

**Comment by DavidGoodwin** [comment]
it'd rely on the underlying driver - if you're using redis or memcache they'll just expire.

If you're using a Stash based cache, then you probably need to call clean() or equivalent on the pool every so often (e.g. if it's a filesystem based thing)

**Comment by vwochnik** [comment]
Thank you! Yes, I am using Stash so I will look into it.
